apiVersion: apps/v1
kind: Deployment

metadata:
  name: github-actions-app

spec:
  replicas: 1

  selector:
    matchLabels:
      app: github-actions-app

  template:
    metadata:
      labels:
        app: github-actions-app

    spec:
      containers:
        - name: app
          image: sujal1250/github-actions-learning:latest
          ports:
            - containerPort: 5000
