name: Deploy to Kubernetes

on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Kubectl
        uses: azure/setup-kubectl@v4

      - name: Configure Kube
        run: |
            mkdir -p $HOME/.kube
            echo "${{ secrets.KUBE_CONFIG }}" > $HOME/.kube/config

      - name: Deploy Application
        run: |
            kubectl apply -f k8s/deployment.yaml
            kubectl apply -f k8s/service.yaml
        
